#!/bin/sh
### BEGIN INIT INFO
# Provides:		DiaperSens
# Required-Start:	$all
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	DiaperSens
### END INIT INFO

DIR=/home/pi/src/git/eldersens/sensedge
DAEMON_USER=root
DAEMON=sensedge.js
DAEMON_NAME=sensedge
PIDFILE=/var/run/${DAEMON_NAME}.pid

. /lib/lsb/init-functions

do_start() {
	log_daemon_msg "Starting system $DAEMON_NAME daemon"
	sleep 10
	hciconfig hci0 reset
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --chdir ${DIR} --startas /bin/bash -- -c "exec node ./$DAEMON > /var/log/$DAEMON_NAME.log 2>&1"
	log_end_msg $?
}

do_stop() {
	log_daemon_msg "Stopping system $DAEMON_NAME daemon"
	kill `cat $PIDFILE`
	sleep 1
	start-stop-daemon --stop --pidfile $PIDFILE --retry 10
	log_end_msg $?
}

case "$1" in
	start|stop)
		do_$1
		;;
	status)
		status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
		;;
	restart|reload|force-reload)
		do_stop
		do_start
		;;
	*)
		echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
		exit 1
		;;
esac

exit 0
